# Generated by Django 5.2.2 on 2025-07-31 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_master_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ai_status',
            field=models.CharField(choices=[('ai_checked_true', '✅ Проверено ИИ'), ('ai_cancelled', '❌ Отклонено ИИ'), ('in_progress', '🔄 В процессе'), ('not_checked', '⏳ Не проверено')], default='not_checked', max_length=20, verbose_name='Статус модерации'),
        ),
    ]
