# Generated by Django 5.2.2 on 2025-07-31 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_review_ai_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='ai_status',
        ),
        migrations.AddField(
            model_name='review',
            name='ai_checked_status',
            field=models.CharField(choices=[('ai_checked_true', 'Проверено ИИ'), ('ai_cancelled', 'Отменено ИИ'), ('ai_checked_in_progress', 'В процессе проверки'), ('ai_checked_false', 'Не проверено')], default='ai_checked_false', max_length=30, verbose_name='Статус ИИ'),
        ),
    ]
